stages:
  - AI
  - Py

variables:
  LINKORID: "https://nhentai.net/g/238404/"
  BARORMOSAIC: "bar"
  STREMOVE: "true"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTHONUNBUFFERED: "1"

# cache packages so subsequent runs are much faster
.cache_python:
  variables:
    FF_USE_FASTZIP: 1  # enable faster caching/artifacting
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:  # cache the venv and pip cache (you may opt to use just 1 of these)
      - venv
      - $PIP_CACHE_DIR

AI:
  variables:
    GRPC_PYTHON_BUILD_SYSTEM_ZLIB: "true"
  stage: AI
  image: python:3.5
  extends: ".cache_python"
  script:
    - python --version  # Print out python version for debugging
    - pip install --upgrade pip
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - apt-get update && apt-get install -y libgl1
    - pip install -r AI/requirements-cpu.txt
    - python AI/main.py $LINKORID $BARORMOSAIC $STREMOVE
  artifacts:
    expire_in: 1 week
    paths:
      - Py/decensor_input/*.png
      - Py/decensor_input_original/*.png

Py:
  tags:
    - gitlab-org # for more ram, otherwise crashes
  stage: Py
  image: python:3.6
  extends: ".cache_python"
  script:
    - python --version
    - pip install --upgrade pip
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r Py/requirements-cpu.txt
    - python Py/decensor.py
  artifacts:
    expire_in: 1 week
    paths:
      - Py/decensor_output/*.png
